import { useEffect, useMemo, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import Building2 from 'lucide-react/dist/esm/icons/building-2.js'
import ExternalLink from 'lucide-react/dist/esm/icons/external-link.js'
import Eye from 'lucide-react/dist/esm/icons/eye.js'
import Link2 from 'lucide-react/dist/esm/icons/link-2.js'
import Palette from 'lucide-react/dist/esm/icons/palette.js'
import Plus from 'lucide-react/dist/esm/icons/plus.js'
import Save from 'lucide-react/dist/esm/icons/save.js'
import Search from 'lucide-react/dist/esm/icons/search.js'
import Users from 'lucide-react/dist/esm/icons/users.js'
import { Field, FormSection, SelectInput, TextArea, TextInput, Toggle } from '../../components/manage/FormControls'
import { ManageShell } from '../../components/manage/ManageShell'
import { apiFetch, backendHref, displayError, jsonBody, queryString } from '../../lib/api'
import { schoolWorkspaceNav } from './schoolWorkspaceNav'
import './ClubWorkspace.css'

type School = { id: number; name: string; logo: string; organizationType: string; slogan: string; address: string; email: string; phone: string; website: string; mapUrl: string; coverPhoto: string; clubDistrict: string; charteredOn: string; sponsoringClub: string; themePrimary: string; themeSecondary: string; themeTernary: string; description: string }
type Shell = { currentSchool: School | null; isSuperAdmin: boolean; user: { displayName: string }; schools: Array<{ id: number; name: string }> }
type Member = { id: number; name: string; photo: string; role: string; identifier: string; committee: string; membershipTerm: string; isVisible: boolean; clubPublished?: boolean; published?: boolean; publicUrl: string }
type ClubSettings = { about: string; hero_left_text: string; hero_right_text: string; hero_quote: string; cta_title: string; cta_subtitle: string; cta_button_label: string; is_public: boolean }
type Social = { id: number; platform: string; url: string; label: string; is_visible: boolean; sort_order: number }
const EMPTY_SETTINGS: ClubSettings = { about: '', hero_left_text: '', hero_right_text: '', hero_quote: '', cta_title: '', cta_subtitle: '', cta_button_label: '', is_public: true }

function schoolId() { return Number(window.location.pathname.match(/^\/dashboard\/organizations\/(\d+)/)?.[1] || 0) }
function clubRoot() { return `/dashboard/organizations/${schoolId()}/club` }

function ClubShell({ shell, title, subtitle, children }: { shell: Shell; title: string; subtitle: string; children: ReactNode }) {
  const school = shell.currentSchool
  return <ManageShell brand={school?.name || 'Club'} brandDetail="Club administration" logo={school?.logo} nav={schoolWorkspaceNav(school?.id, shell.isSuperAdmin, 'club')} title={title} subtitle={subtitle} userName={shell.user.displayName} userRole={shell.isSuperAdmin ? 'Platform administrator' : 'Club manager'} accent={school?.themePrimary || '#00767a'} schoolOptions={shell.isSuperAdmin ? shell.schools : undefined} selectedSchool={school?.id ?? null} onSchoolChange={(id) => { window.location.href = `/dashboard/organizations/${id}/club/` }}>{children}</ManageShell>
}

function useClubShell() {
  const [shell, setShell] = useState<Shell | null>(null); const [error, setError] = useState('')
  useEffect(() => { apiFetch<{ shell: Shell }>(`/api/dashboard/settings/${queryString({ school: schoolId() })}`).then((data) => setShell(data.shell)).catch((reason) => setError(displayError(reason))) }, [])
  return { shell, error }
}

function MobilePreview({ school, settings, sample }: { school: School; settings: ClubSettings; sample?: Member }) {
  return <aside className="club-mobile-preview" aria-label="Club profile preview"><small>Live mobile preview</small><div className="club-preview-phone"><header>{school.logo ? <img src={school.logo} alt="" /> : <Building2 size={18} />}<span><strong>{school.name}</strong><em>{school.slogan || 'Club profile'}</em></span></header><div className="club-preview-cover" style={school.coverPhoto ? { backgroundImage: `url(${backendHref(school.coverPhoto)})` } : undefined}><b>{settings.hero_left_text}</b><b>{settings.hero_right_text}</b></div><section className="club-preview-member">{sample?.photo ? <img src={backendHref(sample.photo)} alt="" /> : <span>{sample?.name?.slice(0, 1) || 'M'}</span>}<div><strong>{sample?.name || 'Club member'}</strong><em>{sample?.role || 'Member'}</em><small>{sample?.identifier || 'Membership ID'}</small></div></section><p>{settings.about || school.description || 'Tell members and visitors about your club.'}</p><dl><div><dt>District</dt><dd>{school.clubDistrict || 'Not set'}</dd></div><div><dt>Club email</dt><dd>{school.email || 'Not set'}</dd></div></dl><footer><strong>{settings.cta_title || 'Let’s build a better tomorrow'}</strong><span>{settings.cta_button_label || 'Let’s connect'}</span></footer></div></aside>
}

export function ClubOverviewPage() {
  const { shell, error } = useClubShell(); const [data, setData] = useState<{ totalMembers: number; publishedProfiles: number; activeMembers: number; socialLinks: number; recentMembers: Member[] } | null>(null)
  useEffect(() => { apiFetch<{ overview: typeof data }>(`/api/dashboard/club-overview/${queryString({ school: schoolId() })}`).then((payload) => setData(payload.overview)).catch(() => undefined) }, [])
  if (!shell) return <div className="manage-state">{error || 'Loading club workspace…'}</div>
  const metrics = [['Total Members', data?.totalMembers || 0, Users], ['Published Profiles', data?.publishedProfiles || 0, Eye], ['Active Members', data?.activeMembers || 0, Users], ['Social Links', data?.socialLinks || 0, Link2]] as const
  return <ClubShell shell={shell} title="Overview" subtitle="Manage your club’s digital identity and members."><div className="club-metrics">{metrics.map(([label, value, Icon]) => <article className="manage-card" key={label}><span><Icon size={19} /></span><small>{label}</small><strong>{value}</strong></article>)}</div><div className="club-overview-grid"><section className="manage-card club-recent"><header><div><h2>Recent members</h2><p>Latest members added to your club.</p></div><a className="manage-button" href={`${clubRoot()}/members/`}>View all</a></header>{data?.recentMembers?.map((member) => <div className="club-member-line" key={member.id}><span>{member.photo ? <img src={backendHref(member.photo)} alt="" /> : member.name.slice(0, 1)}</span><div><strong>{member.name}</strong><small>{member.role || 'Member'} · {member.identifier}</small></div><em className={member.published ? 'is-published' : ''}>{member.published ? 'Published' : 'Unpublished'}</em></div>) || <p className="club-empty">No members yet.</p>}</section><section className="manage-card club-actions"><h2>Quick actions</h2><p>Keep club information and member profiles up to date.</p><a href={`${clubRoot()}/members/`}><Users size={17} />Manage members</a><a href={`${clubRoot()}/club-information/`}><Building2 size={17} />Edit club information</a><a href={`${clubRoot()}/profile-design/`}><Palette size={17} />Edit profile design</a></section></div></ClubShell>
}

export function ClubMembersPage() {
  const { shell, error } = useClubShell(); const [members, setMembers] = useState<Member[]>([]); const [search, setSearch] = useState(''); const [filter, setFilter] = useState('all')
  useEffect(() => { apiFetch<{ members: Member[] }>(`/api/dashboard/members/${queryString({ school: schoolId(), type: 'all' })}`).then((data) => setMembers(data.members)).catch(() => undefined) }, [])
  const shown = useMemo(() => members.filter((member) => (filter === 'all' || (filter === 'published') === Boolean(member.clubPublished)) && [member.name, member.identifier, member.role].join(' ').toLowerCase().includes(search.toLowerCase())), [members, search, filter])
  if (!shell) return <div className="manage-state">{error || 'Loading members…'}</div>
  return <ClubShell shell={shell} title="Members" subtitle="Manage club members and their public-profile settings."><div className="manage-card club-filter"><label><Search size={15} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search name, member ID, or role" /></label><SelectInput value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">All members</option><option value="published">Published</option><option value="unpublished">Unpublished</option></SelectInput><a className="manage-button is-primary" href={`/dashboard/organizations/${schoolId()}/members/?create=member`}><Plus size={14} />Add member</a></div><div className="manage-card club-table-wrap"><table className="club-table"><thead><tr><th>Member</th><th>Role</th><th>Member ID</th><th>Committee</th><th>Term</th><th>Status</th><th /></tr></thead><tbody>{shown.map((member) => <tr key={member.id}><td><span className="club-avatar">{member.photo ? <img src={backendHref(member.photo)} alt="" /> : member.name.slice(0, 1)}</span>{member.name}</td><td>{member.role || '—'}</td><td>{member.identifier || '—'}</td><td>{member.committee || '—'}</td><td>{member.membershipTerm || '—'}</td><td><em className={member.clubPublished ? 'is-published' : ''}>{member.clubPublished ? 'Published' : 'Unpublished'}</em></td><td><a href={`${clubRoot()}/members/${member.id}/`} title="Public profile settings"><Palette size={15} /></a><a href={member.publicUrl} target="_blank" rel="noreferrer" title="View existing card"><ExternalLink size={15} /></a></td></tr>)}</tbody></table></div></ClubShell>
}

function useClubSettings() { const [settings, setSettings] = useState<ClubSettings>(EMPTY_SETTINGS); useEffect(() => { apiFetch<{ settings: ClubSettings }>(`/api/dashboard/club-profile/${queryString({ school: schoolId() })}`).then((data) => setSettings(data.settings)).catch(() => undefined) }, []); return [settings, setSettings] as const }
function SocialEditor() { const [links, setLinks] = useState<Social[]>([]); const [draft, setDraft] = useState({ platform: 'instagram', url: '', label: '' }); useEffect(() => { apiFetch<{ socialLinks: Social[] }>(`/api/dashboard/club-social-links/${queryString({ school: schoolId() })}`).then((data) => setLinks(data.socialLinks)).catch(() => undefined) }, []); const add = async () => { if (!draft.url) return; const response = await apiFetch<{ socialLink: Social }>(`/api/dashboard/club-social-links/${queryString({ school: schoolId() })}`, { method: 'POST', body: jsonBody(draft) }); setLinks((current) => [...current, response.socialLink]); setDraft({ platform: 'instagram', url: '', label: '' }) }; return <FormSection title="Club social links" description="Shown across public club member profiles."><div className="club-social-list">{links.map((link) => <div key={link.id}><strong>{link.platform}</strong><span>{link.url}</span><button type="button" onClick={async () => { await apiFetch(`/api/dashboard/club-social-links/${link.id}/${queryString({ school: schoolId() })}`, { method: 'DELETE' }); setLinks((c) => c.filter((item) => item.id !== link.id)) }}>Remove</button></div>)}</div><div className="club-social-add"><SelectInput value={draft.platform} onChange={(e) => setDraft({ ...draft, platform: e.target.value })}>{['instagram', 'linkedin', 'facebook', 'x', 'tiktok', 'youtube', 'whatsapp', 'other'].map((item) => <option key={item}>{item}</option>)}</SelectInput><TextInput type="url" placeholder="https://" value={draft.url} onChange={(e) => setDraft({ ...draft, url: e.target.value })} /><button className="manage-button" type="button" onClick={add}><Plus size={14} />Add link</button></div></FormSection> }

function MemberSocialEditor({ memberId }: { memberId: number }) { const [links, setLinks] = useState<Social[]>([]); const [draft, setDraft] = useState({ platform: 'linkedin', url: '', label: '' }); const endpoint = `/api/dashboard/club-members/${memberId}/social-links/`; useEffect(() => { if (memberId) apiFetch<{ socialLinks: Social[] }>(`${endpoint}${queryString({ school: schoolId() })}`).then((data) => setLinks(data.socialLinks)).catch(() => undefined) }, [memberId, endpoint]); const add = async () => { if (!draft.url) return; const response = await apiFetch<{ socialLink: Social }>(`${endpoint}${queryString({ school: schoolId() })}`, { method: 'POST', body: jsonBody(draft) }); setLinks((current) => [...current, response.socialLink]); setDraft({ platform: 'linkedin', url: '', label: '' }) }; return <FormSection title="Member social links" description="Optional links for this member only; they do not change club-wide links."><div className="club-social-list">{links.map((link) => <div key={link.id}><strong>{link.platform}</strong><span>{link.url}</span><button type="button" onClick={async () => { await apiFetch(`${endpoint}${link.id}/${queryString({ school: schoolId() })}`, { method: 'DELETE' }); setLinks((current) => current.filter((item) => item.id !== link.id)) }}>Remove</button></div>)}</div><div className="club-social-add"><SelectInput value={draft.platform} onChange={(e) => setDraft({ ...draft, platform: e.target.value })}>{['instagram', 'linkedin', 'facebook', 'x', 'website', 'other'].map((item) => <option key={item}>{item}</option>)}</SelectInput><TextInput type="url" placeholder="https://" value={draft.url} onChange={(e) => setDraft({ ...draft, url: e.target.value })} /><button className="manage-button" type="button" onClick={add}><Plus size={14} />Add link</button></div></FormSection> }

export function ClubProfileDesignPage() { const { shell, error } = useClubShell(); const [settings, setSettings] = useClubSettings(); const [saving, setSaving] = useState(false); const [members, setMembers] = useState<Member[]>([]); useEffect(() => { apiFetch<{ members: Member[] }>(`/api/dashboard/members/${queryString({ school: schoolId(), type: 'all' })}`).then((data) => setMembers(data.members)).catch(() => undefined) }, []); if (!shell) return <div className="manage-state">{error || 'Loading profile design…'}</div>; const update = (key: keyof ClubSettings, value: string | boolean) => setSettings((current) => ({ ...current, [key]: value })); const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { await apiFetch(`/api/dashboard/club-profile/${queryString({ school: schoolId() })}`, { method: 'PATCH', body: jsonBody(settings) }) } finally { setSaving(false) } }; return <ClubShell shell={shell} title="Profile Design" subtitle="Control the shared public club profile presentation."><div className="club-design-layout"><form onSubmit={save}><FormSection title="Branding" description="Logo, cover image, and organization contact details are shared organization data."><a className="manage-button" href={`/dashboard/organizations/${schoolId()}/settings/`}>Edit organization branding</a></FormSection><FormSection title="Hero content"><div className="form-grid"><Field label="Left text"><TextInput value={settings.hero_left_text} onChange={(e) => update('hero_left_text', e.target.value)} /></Field><Field label="Right text"><TextInput value={settings.hero_right_text} onChange={(e) => update('hero_right_text', e.target.value)} /></Field><Field label="Hero quote" wide><TextInput value={settings.hero_quote} onChange={(e) => update('hero_quote', e.target.value)} /></Field></div></FormSection><FormSection title="Call to action"><div className="form-grid"><Field label="Title"><TextInput value={settings.cta_title} onChange={(e) => update('cta_title', e.target.value)} /></Field><Field label="Button label"><TextInput value={settings.cta_button_label} onChange={(e) => update('cta_button_label', e.target.value)} /></Field><Field label="Subtitle" wide><TextArea value={settings.cta_subtitle} onChange={(e) => update('cta_subtitle', e.target.value)} /></Field></div><Toggle label="Publish club profile" checked={settings.is_public} onChange={(value) => update('is_public', value)} /></FormSection><SocialEditor /><button className="manage-button is-primary" disabled={saving}><Save size={14} />{saving ? 'Saving…' : 'Save profile design'}</button></form><MobilePreview school={shell.currentSchool!} settings={settings} sample={members[0]} /></div></ClubShell> }

export function ClubInformationPage() { const { shell, error } = useClubShell(); const [settings, setSettings] = useClubSettings(); if (!shell) return <div className="manage-state">{error || 'Loading club information…'}</div>; const school = shell.currentSchool!; const save = async (event: FormEvent) => { event.preventDefault(); await apiFetch(`/api/dashboard/club-profile/${queryString({ school: schoolId() })}`, { method: 'PATCH', body: jsonBody(settings) }); }; return <ClubShell shell={shell} title="Club Information" subtitle="Shared organization and club profile information."><form className="club-information-form" onSubmit={save}><FormSection title="Organization fields" description="Managed in organization settings and reused by every club member profile."><div className="club-readonly-grid"><span><small>Club name</small><strong>{school.name}</strong></span><span><small>District</small><strong>{school.clubDistrict || 'Not set'}</strong></span><span><small>Chartered on</small><strong>{school.charteredOn || 'Not set'}</strong></span><span><small>Sponsoring club</small><strong>{school.sponsoringClub || 'Not set'}</strong></span><span><small>Public contact</small><strong>{school.email || school.phone || 'Not set'}</strong></span></div><a className="manage-button" href={`/dashboard/organizations/${schoolId()}/settings/`}>Edit organization fields</a></FormSection><FormSection title="About club" description="This content is shared on every club member profile."><Field label="About club"><TextArea value={settings.about} onChange={(e) => setSettings({ ...settings, about: e.target.value })} /></Field></FormSection><button className="manage-button is-primary"><Save size={14} />Save club information</button></form></ClubShell> }

export function ClubMemberProfilePage() { const { shell, error } = useClubShell(); const memberId = Number(window.location.pathname.match(/\/members\/(\d+)/)?.[1]); const [profile, setProfile] = useState<ClubSettings & { quote: string; show_email: boolean; show_phone: boolean; show_address: boolean; show_social_media: boolean; enable_connect: boolean; enable_save_contact: boolean; is_published: boolean }>({ ...EMPTY_SETTINGS, quote: '', show_email: true, show_phone: true, show_address: false, show_social_media: true, enable_connect: true, enable_save_contact: true, is_published: true }); useEffect(() => { if (memberId) apiFetch<{ profile: typeof profile }>(`/api/dashboard/club-members/${memberId}/profile/${queryString({ school: schoolId() })}`).then((data) => setProfile(data.profile)).catch(() => undefined) }, [memberId]); if (!shell) return <div className="manage-state">{error || 'Loading member profile…'}</div>; const toggleKeys = ['show_email', 'show_phone', 'show_address', 'show_social_media', 'enable_connect', 'enable_save_contact', 'is_published'] as const; return <ClubShell shell={shell} title="Member Public Profile" subtitle="Configure visibility without duplicating member identity data."><form onSubmit={async (e) => { e.preventDefault(); await apiFetch(`/api/dashboard/club-members/${memberId}/profile/${queryString({ school: schoolId()})}`, { method: 'PATCH', body: jsonBody(profile) }) }}><FormSection title="Existing member information" description="Name, photo, contact, member ID, role, committee, term, and join date remain in the shared member record."><a className="manage-button" href={`/student/edit/${memberId}`}>Edit member information</a></FormSection><FormSection title="Public profile content"><Field label="Quote"><TextInput value={profile.quote} onChange={(e) => setProfile({ ...profile, quote: e.target.value })} /></Field></FormSection><FormSection title="Visibility and actions">{toggleKeys.map((key) => <Toggle key={key} label={key.replaceAll('_', ' ')} checked={profile[key]} onChange={(value) => setProfile({ ...profile, [key]: value })} />)}</FormSection><MemberSocialEditor memberId={memberId} /><button className="manage-button is-primary"><Save size={14} />Save public profile settings</button></form></ClubShell> }
