# Generated by Django 5.2.4 on 2026-09-19 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gueststay',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_stays', to='hotels.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelorder',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='hotels.hotel'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='hotels.hotel'),
        ),
    ]
