# Generated by Django 5.2.4 on 2026-09-19 13:08

import django.db.models.deletion
import hotels.models
from django.db import migrations, models


def create_feature_settings(apps, schema_editor):
    Hotel = apps.get_model('hotels', 'Hotel')
    Settings = apps.get_model('hotels', 'HotelFeatureSettings')
    for hotel in Hotel.objects.all().iterator():
        defaults = {}
        if hotel.slug == 'hotel-aurora':
            defaults = {'menu_mode': 'ordering', 'service_mode': 'digital_request', 'guest_access_enabled': True}
        Settings.objects.get_or_create(hotel_id=hotel.pk, defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_gueststay_access_code_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelFeatureSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_mode', models.CharField(choices=[('view_only', 'View only'), ('ordering', 'Ordering')], default='view_only', max_length=20)),
                ('service_mode', models.CharField(choices=[('view_only', 'View only'), ('whatsapp', 'WhatsApp'), ('digital_request', 'Digital request')], default='view_only', max_length=24)),
                ('guest_access_enabled', models.BooleanField(default=False)),
                ('menu_visible', models.BooleanField(default=True)),
                ('services_visible', models.BooleanField(default=True)),
                ('offers_visible', models.BooleanField(default=True)),
                ('review_visible', models.BooleanField(default=True)),
                ('contact_links_visible', models.BooleanField(default=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_settings', to='hotels.hotel')),
            ],
            bases=(hotels.models.ValidatedSaveMixin, models.Model),
        ),
        migrations.RunPython(create_feature_settings, migrations.RunPython.noop),
    ]
