# Generated by Django 5.2.4 on 2026-09-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotelfeaturesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelorder',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hotelorder',
            name='idempotency_payload_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='hotelorder',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_stay__isnull', False), ('idempotency_key__gt', '')), fields=('guest_stay', 'idempotency_key'), name='guest_order_idempotency_unique'),
        ),
    ]
