# Generated by Django 5.2.4 on 2026-09-19 15:45

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_hotelorder_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='idempotency_payload_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='public_identifier',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_name_snapshot',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['hotel', 'status', '-created_at'], name='hotels_serv_hotel_i_cc9bdf_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_stay__isnull', False), ('idempotency_key__gt', '')), fields=('guest_stay', 'idempotency_key'), name='guest_service_request_idempotency_unique'),
        ),
    ]
