# Generated by Django 5.2.4 on 2026-09-20 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_servicerequest_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPackageEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('digital_guide', 'Hotel Digital Guide'), ('smart_guest', 'Smart Guest Experience')], default='digital_guide', max_length=32)),
                ('management_mode', models.CharField(choices=[('self_managed', 'Self-managed'), ('tap2connect_managed', 'Tap2connect-managed')], default='self_managed', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hotel_packages', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package_entitlement', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Hotel package entitlement',
            },
        ),
    ]
