# Generated by Django 5.1.7 on 2025-08-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0010_remove_clientprofile_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='student',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='student',
        ),
        migrations.RemoveField(
            model_name='education',
            name='student',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='language',
            name='student',
        ),
        migrations.RemoveField(
            model_name='project',
            name='student',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='vcards.skill'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='vcards.skill'),
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
