# Generated by Django 5.2.4 on 2025-08-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0014_studentprofile_about_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
