# Generated by Django 5.2.4 on 2025-09-01 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0016_journey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='about_current',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='about_featured',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='about_intro',
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('subheadline', models.CharField(blank=True, max_length=255)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero_section', to='vcards.studentprofile')),
            ],
        ),
    ]
