# Generated by Django 5.2.4 on 2025-09-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0017_remove_studentprofile_about_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
