# Generated by Django 5.2.4 on 2025-09-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0019_blogpost_image_certification_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='user_type',
            field=models.CharField(choices=[('general', 'General'), ('vip', 'VIP'), ('premium', 'Premium')], default='general', max_length=10),
        ),
    ]
