# Generated by Django 5.2.4 on 2025-09-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0020_studentprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='social_stack',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
