# Generated by Django 5.2.4 on 2025-09-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0021_studentprofile_social_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='contact_template',
            field=models.CharField(default='contact.html', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio_template',
            field=models.CharField(default='portfolio1.html', max_length=50),
        ),
    ]
