# Generated by Django 5.2.4 on 2026-04-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0024_profileactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='print_custom_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='print_template',
            field=models.CharField(default='print_classic.html', max_length=50),
        ),
    ]
