# Generated by Django 5.2.4 on 2026-04-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0025_studentprofile_print_custom_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='print_back_design',
            field=models.CharField(default='back_qr_clean', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='print_calendar',
            field=models.CharField(default='bs', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='print_card_type',
            field=models.CharField(default='id_card', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='print_front_design',
            field=models.CharField(default='front_academic_blue', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='print_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='print_orientation',
            field=models.CharField(default='portrait', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='print_valid_till',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
