# Generated by Django 5.2.4 on 2026-04-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0026_studentprofile_print_back_design_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='principal_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='college',
            name='principal_signature',
            field=models.ImageField(blank=True, null=True, upload_to='principal_signatures/'),
        ),
        migrations.AddField(
            model_name='college',
            name='theme_light_primary',
            field=models.CharField(blank=True, default='#f7f5f0', max_length=20),
        ),
        migrations.AddField(
            model_name='college',
            name='theme_primary',
            field=models.CharField(blank=True, default='#1a3a5c', max_length=20),
        ),
        migrations.AddField(
            model_name='college',
            name='theme_secondary',
            field=models.CharField(blank=True, default='#1a1a2a', max_length=20),
        ),
        migrations.AddField(
            model_name='college',
            name='theme_ternary',
            field=models.CharField(blank=True, default='#c9a84c', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_level',
            field=models.CharField(blank=True, choices=[('play_group', 'Play Group'), ('pg', 'PG'), ('nursery', 'Nursery'), ('lkg', 'LKG'), ('ukg', 'UKG'), ('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3'), ('grade_4', 'Grade 4'), ('grade_5', 'Grade 5'), ('grade_6', 'Grade 6'), ('grade_7', 'Grade 7'), ('grade_8', 'Grade 8'), ('grade_9', 'Grade 9'), ('grade_10', 'Grade 10'), ('grade_11', 'Grade 11'), ('grade_12', 'Grade 12')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='blood_group',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Not set'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='member_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher / Staff'), ('other', 'Other Member')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_category',
            field=models.CharField(choices=[('school', 'School / College Profile'), ('organization', 'Organization Profile'), ('individual', 'Single Individual Profile'), ('professional', 'Independent Professional')], default='school', max_length=20),
        ),
    ]
