# Generated by Django 5.2.4 on 2026-04-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0028_college_admin_user_studentprofile_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='student',
        ),
        migrations.RemoveField(
            model_name='capability',
            name='student',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='student',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='education',
            name='student',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='student',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='student',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='student',
        ),
        migrations.RemoveField(
            model_name='language',
            name='student',
        ),
        migrations.RemoveField(
            model_name='project',
            name='student',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='student',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='student',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='contact_template',
            field=models.CharField(default='contact2.html', max_length=50),
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Capability',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='Journey',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
