# Generated by Django 5.2.4 on 2026-04-17 09:24

from django.db import migrations, models


def populate_unique_identifiers(apps, schema_editor):
    StudentProfile = apps.get_model('vcards', 'StudentProfile')
    for profile in StudentProfile.objects.all().iterator():
        if profile.unique_identifier:
            continue

        school_part = f"S{profile.college_id}" if profile.college_id else "GEN"
        type_part = {
            'student': 'STU',
            'teacher': 'TCH',
            'staff': 'STF',
            'other': 'MEM',
        }.get(profile.member_type, 'MEM')
        profile.unique_identifier = f"{school_part}-{type_part}-{profile.pk:05d}"
        profile.save(update_fields=['unique_identifier'])


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0029_remove_blogpost_student_remove_capability_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='unique_identifier',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, unique=True),
        ),
        migrations.RunPython(populate_unique_identifiers, migrations.RunPython.noop),
    ]
