# Generated by Django 5.2.4 on 2026-09-11 17:04

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0038_platform_module_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('cards_printed', models.PositiveIntegerField(default=0)),
                ('faulty_cards', models.PositiveIntegerField(default=0)),
                ('reprinted_cards', models.PositiveIntegerField(default=0)),
                ('cards_sold', models.PositiveIntegerField(default=0)),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fault_reprint_reason', models.CharField(blank=True, choices=[('printing_issue', 'Printing issue'), ('nfc_not_working', 'NFC not working'), ('wrong_details', 'Wrong details'), ('damaged', 'Damaged'), ('qr_issue', 'QR issue'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='platformaccess',
            options={'default_permissions': (), 'permissions': [('access_platform_overview', 'Can access platform overview'), ('access_platform_organizations', 'Can access platform organizations'), ('access_platform_members', 'Can access platform members'), ('access_platform_professionals', 'Can access platform professional profiles'), ('access_platform_templates', 'Can access platform Template Studio'), ('access_platform_cards', 'Can access platform cards'), ('access_platform_card_operations', 'Can access platform card operations'), ('access_platform_activity', 'Can access platform activity'), ('access_platform_reports', 'Can access platform reports'), ('access_platform_settings', 'Can access platform settings')]},
        ),
    ]
