# Generated by Django 5.2.4 on 2026-09-11 17:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_cards', '0018_professionalprofile_google_review_url'),
        ('vcards', '0039_cardbatch_alter_platformaccess_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBatchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_label', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('faulty', 'Faulty'), ('reprinted', 'Reprinted'), ('sold', 'Sold')], default='available', max_length=20)),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_cards', to='vcards.cardbatch')),
                ('professional_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_card_entries', to='professional_cards.professionalprofile')),
                ('student_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_card_entries', to='vcards.studentprofile')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('student_profile__isnull', True), ('professional_profile__isnull', True), _connector='OR'), name='card_batch_card_at_most_one_profile')],
            },
        ),
    ]
