# Generated by Django 5.2.4 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('vcards', '0040_cardbatchcard')]

    operations = [
        migrations.AddField(
            model_name='college', name='organization_type',
            field=models.CharField(blank=True, choices=[('education', 'Education'), ('club', 'Club'), ('business', 'Business'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile', name='member_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('staff', 'Staff / Administration'), ('member', 'Member'), ('other', 'Other Member')], default='student', max_length=20),
        ),
        migrations.AddField(model_name='studentprofile', name='academic_year', field=models.CharField(blank=True, default='', max_length=40)),
        migrations.AddField(model_name='studentprofile', name='faculty_program', field=models.CharField(blank=True, default='', max_length=120)),
        migrations.AddField(model_name='studentprofile', name='department', field=models.CharField(blank=True, default='', max_length=120)),
        migrations.AddField(model_name='studentprofile', name='committee', field=models.CharField(blank=True, default='', max_length=120)),
        migrations.AddField(model_name='studentprofile', name='membership_term', field=models.CharField(blank=True, default='', max_length=60)),
        migrations.AddField(model_name='studentprofile', name='join_date', field=models.DateField(blank=True, null=True)),
    ]
