# Generated by Django 5.2.4 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('vcards', '0041_education_club_organization_modules')]

    operations = [
        migrations.AddField(
            model_name='college',
            name='organization_code',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, unique=True),
        ),
    ]
