# Generated by Django 5.2.4 on 2026-09-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0044_studentprofile_password_change_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='chartered_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='club_district',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='college',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_covers/'),
        ),
        migrations.AddField(
            model_name='college',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='sponsoring_club',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='college',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
