# Generated by Django 5.2.4 on 2026-09-20 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0045_club_template_organization_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(blank=True, default='', max_length=180)),
                ('show_email', models.BooleanField(default=True)),
                ('show_phone', models.BooleanField(default=True)),
                ('show_address', models.BooleanField(default=False)),
                ('show_social_media', models.BooleanField(default=True)),
                ('enable_connect', models.BooleanField(default=True)),
                ('enable_save_contact', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_public_profile', to='vcards.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClubProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, default='')),
                ('hero_left_text', models.CharField(blank=True, default='', max_length=100)),
                ('hero_right_text', models.CharField(blank=True, default='', max_length=100)),
                ('hero_quote', models.CharField(blank=True, default='', max_length=180)),
                ('cta_title', models.CharField(blank=True, default='', max_length=120)),
                ('cta_subtitle', models.CharField(blank=True, default='', max_length=180)),
                ('cta_button_label', models.CharField(blank=True, default='', max_length=60)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_profile_settings', to='vcards.college')),
            ],
        ),
        migrations.CreateModel(
            name='ClubMemberSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, default='', max_length=60)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_social_links', to='vcards.studentprofile')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('member', 'platform', 'url'), name='club_member_social_link_unique')],
            },
        ),
        migrations.CreateModel(
            name='ClubSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('x', 'X'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=30)),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, default='', max_length=60)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_social_links', to='vcards.college')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('organization', 'platform', 'url'), name='club_social_link_unique')],
            },
        ),
    ]
