# Generated by Django 5.2.4 on 2026-09-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0048_normalize_club_member_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformaccess',
            options={'default_permissions': (), 'permissions': [('access_platform_overview', 'Can access platform overview'), ('access_platform_organizations', 'Can access platform organizations'), ('access_platform_hotels', 'Can access platform hotels'), ('access_platform_members', 'Can access platform members'), ('access_platform_professionals', 'Can access platform professional profiles'), ('access_platform_templates', 'Can access platform Template Studio'), ('access_platform_cards', 'Can access platform cards'), ('access_platform_card_operations', 'Can access platform card operations'), ('access_platform_activity', 'Can access platform activity'), ('access_platform_reports', 'Can access platform reports'), ('access_platform_settings', 'Can access platform settings')]},
        ),
    ]
