# Generated by Django 5.2.4 on 2026-09-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0049_alter_platformaccess_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformaccess',
            options={'default_permissions': (), 'permissions': [('access_platform_overview', 'Can access platform overview'), ('access_platform_organizations', 'Can access platform organizations'), ('access_platform_members', 'Can access platform members'), ('access_platform_professionals', 'Can access platform professional profiles'), ('access_platform_templates', 'Can access platform Template Studio'), ('access_platform_cards', 'Can access platform cards'), ('access_platform_card_operations', 'Can access platform card operations'), ('access_platform_activity', 'Can access platform activity'), ('access_platform_reports', 'Can access platform reports'), ('access_platform_settings', 'Can access platform settings')]},
        ),
        migrations.AlterField(
            model_name='college',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('education', 'Education'), ('club', 'Club'), ('business', 'Business'), ('hospitality', 'Hospitality'), ('other', 'Other')], default='', max_length=20),
        ),
    ]
