# Generated by Codex on 2026-06-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Used for the public profile URL.', max_length=180, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='professional_profiles/photos/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='professional_profiles/covers/')),
                ('designation', models.CharField(blank=True, default='', max_length=160)),
                ('company_name', models.CharField(blank=True, default='', max_length=180)),
                ('industry', models.CharField(blank=True, default='', max_length=120)),
                ('short_tagline', models.CharField(blank=True, default='', max_length=255)),
                ('about', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('booking_url', models.URLField(blank=True, default='')),
                ('office_address', models.TextField(blank=True, default='')),
                ('google_maps_url', models.URLField(blank=True, default='')),
                ('business_hours', models.CharField(blank=True, default='', max_length=180)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=160)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('template_name', models.CharField(choices=[('professional_premium', 'Professional Premium')], default='professional_premium', max_length=80)),
                ('accent_color', models.CharField(default='#0f766e', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to='professional_profiles/documents/')),
                ('document_type', models.CharField(choices=[('brochure', 'Brochure'), ('portfolio', 'Portfolio'), ('certificate', 'Certificate'), ('other', 'Other')], default='other', max_length=30)),
                ('is_public', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='professional_cards.professionalprofile')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='professional_profiles/portfolio/')),
                ('link', models.URLField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='professional_cards.professionalprofile')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='professional_cards.professionalprofile')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=160)),
                ('client_role', models.CharField(blank=True, default='', max_length=180)),
                ('review_text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='professional_cards.professionalprofile')),
            ],
            options={
                'ordering': ['display_order', 'client_name'],
            },
        ),
    ]
