# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='profile_type',
            field=models.CharField(
                choices=[
                    ('student', 'Student'),
                    ('professional', 'Professional'),
                    ('entrepreneur', 'Entrepreneur'),
                    ('creator', 'Creator'),
                    ('other', 'Other'),
                ],
                default='professional',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
