# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_cards', '0002_networking_profile_type_and_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='show_map_on_profile',
            field=models.BooleanField(default=False),
        ),
    ]
