# Generated by Django 5.2.4 on 2026-07-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_cards', '0006_professionalprofile_academic_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaldocument',
            name='document_type',
            field=models.CharField(choices=[('cv_resume', 'CV / Resume'), ('brochure', 'Brochure'), ('portfolio', 'Portfolio'), ('certificate', 'Certificate'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
