# Generated by Django 5.2.4 on 2026-07-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_cards', '0008_modern_identity_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalportfolioitem',
            name='highlight_type',
            field=models.CharField(choices=[('project', 'Project'), ('work_experience', 'Work experience'), ('internship', 'Internship'), ('achievement', 'Achievement'), ('volunteering', 'Volunteering'), ('event', 'Event'), ('publication', 'Publication'), ('other', 'Other')], default='project', max_length=40),
        ),
        migrations.AddField(
            model_name='professionalportfolioitem',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='professionalportfolioitem',
            name='period',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='brand_tagline',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='current_status',
            field=models.CharField(blank=True, choices=[('', 'Select status'), ('opportunities', 'Open to opportunities'), ('internships', 'Open to internships'), ('freelance', 'Open to freelance projects'), ('collaboration', 'Open to collaboration'), ('mentorship', 'Open to mentorship'), ('not_available', 'Currently not available')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='header_identity',
            field=models.CharField(choices=[('organization', 'Organization'), ('personal', 'Personal brand'), ('hidden', 'Hide header identity')], default='organization', max_length=30),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='looking_for',
            field=models.CharField(blank=True, default='', help_text='Comma-separated opportunity interests selected in the profile builder.', max_length=255),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='networking_statement',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='personal_logo',
            field=models.ImageField(blank=True, null=True, upload_to='professional_profiles/personal_logos/'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='preferred_work_mode',
            field=models.CharField(blank=True, choices=[('', 'Select work mode'), ('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('flexible', 'Flexible')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='professionaltestimonial',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='professionaltestimonial',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='professional_profiles/recommendations/'),
        ),
    ]
