# Generated by Django 5.2.4 on 2026-07-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_cards', '0009_professionalportfolioitem_highlight_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='academic_address',
            field=models.TextField(blank=True, default='', help_text='Address shown only in the Academic Identity card.'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='work_address',
            field=models.TextField(blank=True, default='', help_text='Address shown only in the Work Identity card.'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='work_experience',
            field=models.CharField(blank=True, default='', help_text='Experience shown only in the Work Identity card.', max_length=120),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='work_organization',
            field=models.CharField(blank=True, default='', help_text='Organization shown only in the Work Identity card.', max_length=180),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='work_role',
            field=models.CharField(blank=True, default='', help_text='Role shown only in the Work Identity card.', max_length=160),
        ),
    ]
