# Generated by Django 5.2.4 on 2026-07-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_cards', '0010_professionalprofile_academic_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='academic_status',
            field=models.CharField(blank=True, default='', help_text='Status shown only in the Academic Identity card.', max_length=160),
        ),
    ]
