# Generated by Django 5.2.4 on 2026-07-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_cards', '0011_professionalprofile_academic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='template_name',
            field=models.CharField(choices=[('modern_identity', 'Modern Identity'), ('organization_focus', 'Organization Focus')], default='modern_identity', max_length=80),
        ),
    ]
