# Generated by Codex on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_cards', '0012_alter_professionalprofile_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='primary_cta_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='primary_cta_type',
            field=models.CharField(choices=[('contact', 'Contact'), ('website', 'Visit Website'), ('booking', 'Book a Meeting'), ('save_contact', 'Save Contact'), ('custom', 'Custom Link')], default='contact', max_length=30),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='primary_cta_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='show_primary_cta',
            field=models.BooleanField(default=True),
        ),
    ]
