# Generated by Codex on 2026-08-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_cards', '0013_professionalprofile_primary_cta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connection_requests', to='professional_cards.professionalprofile')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connection_requests', to='professional_cards.professionalprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='professionalconnection',
            constraint=models.UniqueConstraint(fields=('requester', 'recipient'), name='unique_professional_connection_direction'),
        ),
        migrations.AddConstraint(
            model_name='professionalconnection',
            constraint=models.CheckConstraint(condition=models.Q(('requester', models.F('recipient')), _negated=True), name='professional_connection_not_self'),
        ),
    ]
