# Generated by Django 5.2.4 on 2026-09-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_cards', '0017_professionalprofile_tiktok_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='google_review_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
