# Generated by Django 5.2.4 on 2026-07-31 04:55

import card_designer.models
import card_designer.storage
import card_designer.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('asset_type', models.CharField(choices=[('profile_photo', 'Profile photo'), ('company_logo', 'Company logo'), ('school_logo', 'School logo'), ('background', 'Background'), ('signature', 'Signature'), ('decoration', 'Decorative image'), ('icon', 'Custom icon'), ('brand', 'Official brand asset')], default='decoration', max_length=32)),
                ('file', models.FileField(storage=card_designer.storage.PrivateCardMediaStorage(), upload_to=card_designer.models.private_asset_upload_to, validators=[card_designer.validators.validate_design_asset])),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_assets', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_card_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('professional', 'Professional'), ('corporate', 'Corporate'), ('minimal', 'Minimal'), ('creative', 'Creative'), ('student', 'Student'), ('teacher', 'Teacher'), ('doctor', 'Doctor'), ('engineer', 'Engineer'), ('business', 'Business'), ('school', 'School'), ('premium', 'Premium')], default='professional', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('front_data', models.JSONField(default=dict)),
                ('back_data', models.JSONField(default=dict)),
                ('supports_back', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('eligible_account_types', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.FileField(blank=True, null=True, storage=card_designer.storage.PrivateCardMediaStorage(), upload_to=card_designer.models.template_thumbnail_upload_to, validators=[card_designer.validators.validate_design_asset])),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_card_templates', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_card_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CardDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled card', max_length=140)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for review'), ('ordered', 'Ordered'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('finish', models.CharField(choices=[('pvc', 'PVC'), ('metal', 'Metal'), ('wood', 'Wood')], default='pvc', max_length=20)),
                ('front_data', models.JSONField(default=dict)),
                ('back_data', models.JSONField(default=dict)),
                ('source_template_version', models.PositiveIntegerField(blank=True, null=True)),
                ('current_revision', models.PositiveIntegerField(default=0)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_designs', to=settings.AUTH_USER_MODEL)),
                ('source_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_designs', to='card_designer.cardtemplate')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CardDesignRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=140)),
                ('finish', models.CharField(max_length=20)),
                ('front_data', models.JSONField(default=dict)),
                ('back_data', models.JSONField(default=dict)),
                ('reason', models.CharField(default='manual', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_design_revisions', to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='card_designer.carddesign')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('design', 'version'), name='unique_card_design_revision')],
            },
        ),
        migrations.CreateModel(
            name='CardTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(max_length=32)),
                ('front_data', models.JSONField(default=dict)),
                ('back_data', models.JSONField(default=dict)),
                ('supports_back', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('eligible_account_types', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_card_template_versions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='card_designer.cardtemplate')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('template', 'version'), name='unique_card_template_version')],
            },
        ),
    ]
