# Generated by Django 5.2.4 on 2026-09-28 17:43

import django.core.validators
import django.db.models.deletion
import hospitality.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vcards', '0050_alter_platformaccess_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Café'), ('bar', 'Bar'), ('other', 'Other venue')], default='restaurant', max_length=20)),
                ('public_identifier', models.CharField(default=hospitality.models.public_identifier, editable=False, max_length=64, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='venue_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='venue_covers/')),
                ('description', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#173f35', max_length=20)),
                ('secondary_color', models.CharField(default='#bd6848', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('whatsapp', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('map_url', models.URLField(blank=True)),
                ('google_review_url', models.URLField(blank=True)),
                ('feedback_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue_profile', to='vcards.college')),
            ],
        ),
        migrations.CreateModel(
            name='VenueMenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='hospitality.venueprofile')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VenueLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='hospitality.venueprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VenueFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='new', max_length=20)),
                ('rate_limit_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='hospitality.venueprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VenueMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='venue_menu/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('dietary_info', models.CharField(blank=True, max_length=255)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_today_special', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='hospitality.venuemenucategory')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='hospitality.venueprofile')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['venue', 'is_available', 'display_order'], name='hospitality_venue_i_3e1654_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='venuemenucategory',
            constraint=models.UniqueConstraint(fields=('venue', 'slug'), name='venue_menu_category_slug_unique'),
        ),
        migrations.AddIndex(
            model_name='venuelink',
            index=models.Index(fields=['venue', 'is_active', 'display_order'], name='hospitality_venue_i_4a3f26_idx'),
        ),
    ]
