# Generated by Django 5.2.4 on 2026-10-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0006_expand_hospitality_profile_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueanalyticsevent',
            name='event_type',
            field=models.CharField(choices=[('profile_view', 'Profile view'), ('menu_open', 'Menu opened'), ('menu_item_click', 'Menu item clicked'), ('rating_click', 'Rating clicked'), ('google_review_click', 'Google review button clicked'), ('feedback_submit', 'Feedback submitted'), ('social_click', 'Social link clicked')], max_length=32),
        ),
    ]
