from django import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, re_path
from django.views.static import serve as serve_media
from django.contrib import admin
from shops.views import business_suite
from vcards.views import *
from vcards.views import dashboard_qr_export, dashboard_qr_export_download
from vcard_backend import react_api
from vcard_backend.react_views import react_app

urlpatterns = [
    path('', react_app, name='home'),
    path('robots.txt', robots_txt, name='robots_txt'),
    path('sitemap.xml', sitemap_xml, name='sitemap_xml'),
    path('shop/', include('shops.urls')),
    path('', include('professional_cards.urls')),
    path('login/', react_app, name='dashboard_login'),
    path('card-editor/', react_app, name='card_editor'),
    path('logout/', dashboard_logout, name='dashboard_logout'),
    path('profile/<int:student_id>/', react_app, name='profile'),
    path('admin/', admin.site.urls),
    path('dashboard/', react_app, name='admin_dashboard'),
    path('dashboard/templates/', react_app, name='dashboard_template_studio'),
    path('dashboard/business-suite/', react_app, name='business_suite'),
    path('dashboard/schools/', react_app, name='dashboard_schools'),
    path('dashboard/students/', react_app, name='dashboard_students'),
    path('dashboard/teachers/', react_app, name='dashboard_teachers'),
    path('dashboard/reports/', react_app, name='dashboard_reports'),
    path('dashboard/settings/', react_app, name='dashboard_settings'),
    path('dashboard/print/', react_app, name='dashboard_print'),
    path('dashboard/qr-export/', react_app, name='dashboard_qr_export'),
    path('dashboard/print/preview/', dashboard_print_preview, name='dashboard_print_preview'),
    path('dashboard/print/export-pdf/', dashboard_print_export_pdf, name='dashboard_print_export_pdf'),
    path('dashboard/qr-export/download/', dashboard_qr_export_download, name='dashboard_qr_export_download'),
    path('dashboard/bulk-upload/', react_app, name='dashboard_bulk_upload'),
    path('dashboard/create/', react_app, name='add_user'),
    path('dashboard/college_details/<int:college_id>/', react_app, name='college_details'),
    path('dashboard/edit_college/<int:college_id>/', react_app, name='edit_college'),
    path('dashboard/add_college/', react_app, name='add_college'),
    path('dashboard/delete_college/<int:college_id>/', react_app, name='delete_college'),
    path('student/<int:student_id>/login/', react_app, name='edit_student_auth'),
    path('student/<int:student_id>/logout/', logout_student_edit, name='logout_student_edit'),
    path('student/<int:student_id>/manage/', react_app, name='student_owner_dashboard'),
    path('dashboard/edit/<int:student_id>/', react_app, name='edit_student'),
    path('dashboard/student/<int:student_id>/credentials/', react_app, name='student_credentials'),
    path('dashboard/delete/<int:student_id>/', react_app, name='delete_student_profile'),
    path('dashboard/reset-password/<int:student_id>/', react_app, name='reset_student_password'),
    path('dashboard/students/assign-usernames/', react_app, name='assign_school_usernames'),
    path('bulk-upload/', react_app, name='bulk_upload'),
    path('dashboard/college/<int:college_id>/add_student/', react_app, name='add_student_to_college'),
    path('student/<int:student_id>/', react_app, name='contact_card'),
    path('student/<int:student_id>/contact-card/', react_app, name='student_contact_card'),
    path('student/<int:student_id>/action/<slug:action>/', track_contact_action, name='track_contact_action'),
    path('student/<int:student_id>/download-vcard/', download_vcard, name='download_vcard'),
    path('student/<int:student_id>/birth-certificate/', view_birth_certificate, name='view_birth_certificate'),
    path('student/<int:student_id>/print-preview/', print_card_preview, name='print_card_preview'),
    path('student/<int:student_id>/print-qr.png', print_qr_code, name='print_qr_code'),
    path('student/edit/<int:student_id>', react_app, name='edit_student_manual'),
    path('ai-chat/', react_app, name='ai_chat'),
    path('send-message/', send_site_message, name='send_message'),
    path('api/card/lookup/', api_card_lookup, name='api_card_lookup'),
    path('api/dashboard/overview/', dashboard_overview_api, name='dashboard_overview_api'),
    path('api/session/', react_api.session_api, name='react_session_api'),
    path('api/session/login/', react_api.session_login_api, name='react_session_login_api'),
    path('api/session/logout/', react_api.session_logout_api, name='react_session_logout_api'),
    path('api/card-designer/', include('card_designer.urls')),
    path('api/manage/professional-profiles/', react_api.professional_profiles_manage_api, name='react_professional_profiles_api'),
    path('api/manage/professional-profiles/<int:pk>/', react_api.professional_profile_manage_api, name='react_professional_profile_api'),
    path('api/manage/professional-profiles/by-slug/<slug:slug>/', react_api.professional_profile_owner_api, name='react_professional_profile_owner_api'),
    path('api/professional-profiles/<slug:slug>/edit-login/', react_api.professional_profile_login_api, name='react_professional_login_api'),
    path('api/students/<int:student_id>/', react_api.student_public_api, name='react_student_public_api'),
    path('api/students/<int:student_id>/edit-login/', react_api.student_login_api, name='react_student_login_api'),
    path('api/manage/students/<int:student_id>/', react_api.student_manage_api, name='react_student_manage_api'),
    path('api/manage/students/<int:student_id>/dashboard/', react_api.student_owner_dashboard_api, name='react_student_dashboard_api'),
    path('api/dashboard/schools/', react_api.dashboard_schools_api, name='react_dashboard_schools_api'),
    path('api/dashboard/schools/<int:school_id>/', react_api.dashboard_school_api, name='react_dashboard_school_api'),
    path('api/dashboard/members/', react_api.dashboard_members_api, name='react_dashboard_members_api'),
    path('api/dashboard/reports/', react_api.dashboard_reports_api, name='react_dashboard_reports_api'),
    path('api/dashboard/settings/', react_api.dashboard_settings_api, name='react_dashboard_settings_api'),
    path('api/dashboard/credentials/<int:student_id>/', react_api.dashboard_credentials_api, name='react_dashboard_credentials_api'),
    path('api/dashboard/bulk-upload/', react_api.dashboard_bulk_upload_api, name='react_dashboard_bulk_upload_api'),
    path('api/dashboard/print-controls/', react_api.dashboard_print_controls_api, name='react_dashboard_print_controls_api'),
    path('api/shops/<slug:store_slug>/', react_api.shop_public_api, name='react_shop_public_api'),
    path('api/shops/<slug:store_slug>/products/<slug:product_slug>/', react_api.shop_product_public_api, name='react_shop_product_public_api'),
    path('api/shops/<slug:store_slug>/cart/', react_api.shop_cart_api, name='react_shop_cart_api'),
    path('api/shops/<slug:store_slug>/checkout/', react_api.shop_checkout_api, name='react_shop_checkout_api'),
    path('api/shops/<slug:store_slug>/orders/<str:order_number>/', react_api.shop_order_public_api, name='react_shop_order_public_api'),
    path('api/shops/<slug:store_slug>/track-order/', react_api.shop_track_order_api, name='react_shop_track_order_api'),
    path('api/shops/<slug:store_slug>/owner/', react_api.shop_owner_dashboard_api, name='react_shop_owner_dashboard_api'),
    path('api/shops/<slug:store_slug>/owner/products/', react_api.shop_owner_products_api, name='react_shop_owner_products_api'),
    path('api/shops/<slug:store_slug>/owner/products/<int:product_id>/', react_api.shop_owner_product_api, name='react_shop_owner_product_api'),
    path('api/shops/<slug:store_slug>/owner/categories/', react_api.shop_owner_categories_api, name='react_shop_owner_categories_api'),
    path('api/shops/<slug:store_slug>/owner/categories/<int:category_id>/', react_api.shop_owner_category_api, name='react_shop_owner_category_api'),
    path('api/shops/<slug:store_slug>/owner/customers/', react_api.shop_owner_customers_api, name='react_shop_owner_customers_api'),
    path('api/shops/<slug:store_slug>/owner/orders/', react_api.shop_owner_orders_api, name='react_shop_owner_orders_api'),
    path('api/shops/<slug:store_slug>/owner/orders/<int:order_id>/', react_api.shop_owner_order_api, name='react_shop_owner_order_api'),
    path('api/shops/<slug:store_slug>/owner/discounts/', react_api.shop_owner_discounts_api, name='react_shop_owner_discounts_api'),
    path('api/shops/<slug:store_slug>/owner/discounts/<int:discount_id>/', react_api.shop_owner_discount_api, name='react_shop_owner_discount_api'),
    path('api/shops/<slug:store_slug>/owner/website/', react_api.shop_owner_website_api, name='react_shop_owner_website_api'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__reload__/", include("django_browser_reload.urls"))]
elif settings.SERVE_MEDIA_FILES:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve_media, {'document_root': settings.MEDIA_ROOT}),
    ]
