from django import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin
from vcards.views import *
from vcards.views import dashboard_qr_export, dashboard_qr_export_download
from vcard_backend import react_api
from vcard_backend.health import health_check
from vcard_backend.react_views import react_app

urlpatterns = [
    path('health/', health_check, name='health_check'),
    path('', react_app, name='home'),
    path('robots.txt', robots_txt, name='robots_txt'),
    path('sitemap.xml', sitemap_xml, name='sitemap_xml'),
    path('', include('professional_cards.urls')),
    path('login/', react_app, name='dashboard_login'),
    path('platform/login/', react_app, name='platform_login'),
    path('card-editor/', react_app, name='card_editor'),
    path('logout/', dashboard_logout, name='dashboard_logout'),
    path('profile/<int:student_id>/', react_app, name='profile'),
    path('admin/', admin.site.urls),
    path('dashboard/', react_app, name='admin_dashboard'),
    path('dashboard/templates/', react_app, name='dashboard_template_studio'),
    path('dashboard/schools/', react_app, name='dashboard_schools'),
    path('dashboard/organizations/<int:organization_id>/', react_app, name='dashboard_organization_workspace'),
    path('dashboard/organizations/<int:organization_id>/members/', react_app, name='dashboard_organization_members'),
    path('dashboard/organizations/<int:organization_id>/members/<int:student_id>/credentials/', react_app, name='dashboard_organization_member_credentials'),
    path('dashboard/organizations/<int:organization_id>/bulk-upload/', react_app, name='dashboard_organization_bulk_upload'),
    path('dashboard/organizations/<int:organization_id>/print/', react_app, name='dashboard_organization_print'),
    path('dashboard/organizations/<int:organization_id>/exports/', react_app, name='dashboard_organization_exports'),
    path('dashboard/organizations/<int:organization_id>/reports/', react_app, name='dashboard_organization_reports'),
    path('dashboard/organizations/<int:organization_id>/settings/', react_app, name='dashboard_organization_settings'),
    path('dashboard/students/', react_app, name='dashboard_students'),
    path('dashboard/teachers/', react_app, name='dashboard_teachers'),
    path('dashboard/reports/', react_app, name='dashboard_reports'),
    path('dashboard/activity/', react_app, name='dashboard_activity'),
    path('dashboard/settings/staff-access/', react_app, name='dashboard_platform_staff_access'),
    path('dashboard/settings/', react_app, name='dashboard_settings'),
    path('dashboard/print/', react_app, name='dashboard_print'),
    path('dashboard/qr-export/', react_app, name='dashboard_qr_export'),
    path('dashboard/print/preview/', dashboard_print_preview, name='dashboard_print_preview'),
    path('dashboard/print/export-pdf/', dashboard_print_export_pdf, name='dashboard_print_export_pdf'),
    path('dashboard/qr-export/download/', dashboard_qr_export_download, name='dashboard_qr_export_download'),
    path('dashboard/bulk-upload/', react_app, name='dashboard_bulk_upload'),
    path('dashboard/create/', react_app, name='add_user'),
    path('dashboard/college_details/<int:college_id>/', react_app, name='college_details'),
    path('dashboard/edit_college/<int:college_id>/', react_app, name='edit_college'),
    path('dashboard/add_college/', react_app, name='add_college'),
    path('dashboard/delete_college/<int:college_id>/', react_app, name='delete_college'),
    path('student/<int:student_id>/login/', react_app, name='edit_student_auth'),
    path('student/<int:student_id>/logout/', logout_student_edit, name='logout_student_edit'),
    path('student/<int:student_id>/manage/', react_app, name='student_owner_dashboard'),
    path('dashboard/edit/<int:student_id>/', react_app, name='edit_student'),
    path('dashboard/student/<int:student_id>/credentials/', react_app, name='student_credentials'),
    path('dashboard/delete/<int:student_id>/', react_app, name='delete_student_profile'),
    path('dashboard/reset-password/<int:student_id>/', react_app, name='reset_student_password'),
    path('dashboard/students/assign-usernames/', react_app, name='assign_school_usernames'),
    path('bulk-upload/', react_app, name='bulk_upload'),
    path('dashboard/college/<int:college_id>/add_student/', react_app, name='add_student_to_college'),
    path('student/<int:student_id>/', react_app, name='contact_card'),
    path('student/<int:student_id>/contact-card/', react_app, name='student_contact_card'),
    path('student/<int:student_id>/action/<slug:action>/', track_contact_action, name='track_contact_action'),
    path('student/<int:student_id>/download-vcard/', download_vcard, name='download_vcard'),
    path('student/<int:student_id>/birth-certificate/', view_birth_certificate, name='view_birth_certificate'),
    path('student/<int:student_id>/print-preview/', print_card_preview, name='print_card_preview'),
    path('student/<int:student_id>/print-qr.png', print_qr_code, name='print_qr_code'),
    path('student/edit/<int:student_id>', react_app, name='edit_student_manual'),
    path('ai-chat/', react_app, name='ai_chat'),
    path('send-message/', send_site_message, name='send_message'),
    path('api/card/lookup/', api_card_lookup, name='api_card_lookup'),
    path('api/dashboard/overview/', dashboard_overview_api, name='dashboard_overview_api'),
    path('api/session/', react_api.session_api, name='react_session_api'),
    path('api/session/login/', react_api.session_login_api, name='react_session_login_api'),
    path('api/platform/session/login/', react_api.platform_session_login_api, name='react_platform_session_login_api'),
    path('api/session/logout/', react_api.session_logout_api, name='react_session_logout_api'),
    path('api/dashboard/platform-staff/', react_api.platform_staff_api, name='react_platform_staff_api'),
    path('api/dashboard/platform-staff/<int:user_id>/', react_api.platform_staff_detail_api, name='react_platform_staff_detail_api'),
    path('api/card-designer/', include('card_designer.urls')),
    path('api/manage/professional-profiles/', react_api.professional_profiles_manage_api, name='react_professional_profiles_api'),
    path('api/manage/professional-profiles/<int:pk>/', react_api.professional_profile_manage_api, name='react_professional_profile_api'),
    path('api/manage/professional-profiles/by-slug/<slug:slug>/', react_api.professional_profile_owner_api, name='react_professional_profile_owner_api'),
    path('api/professional-profiles/<slug:slug>/edit-login/', react_api.professional_profile_login_api, name='react_professional_login_api'),
    path('api/professional-profiles/<slug:slug>/connect/', react_api.professional_connection_request_api, name='react_professional_connection_request_api'),
    path('api/connections/', react_api.professional_connections_api, name='react_professional_connections_api'),
    path('api/connections/<int:connection_id>/respond/', react_api.professional_connection_response_api, name='react_professional_connection_response_api'),
    path('api/connections/<int:connection_id>/manage/', react_api.professional_connection_manage_api, name='react_professional_connection_manage_api'),
    path('api/students/<int:student_id>/', react_api.student_public_api, name='react_student_public_api'),
    path('api/students/<int:student_id>/edit-login/', react_api.student_login_api, name='react_student_login_api'),
    path('api/manage/students/<int:student_id>/', react_api.student_manage_api, name='react_student_manage_api'),
    path('api/manage/students/<int:student_id>/dashboard/', react_api.student_owner_dashboard_api, name='react_student_dashboard_api'),
    path('api/dashboard/schools/', react_api.dashboard_schools_api, name='react_dashboard_schools_api'),
    path('api/dashboard/schools/<int:school_id>/', react_api.dashboard_school_api, name='react_dashboard_school_api'),
    path('api/dashboard/members/', react_api.dashboard_members_api, name='react_dashboard_members_api'),
    path('api/dashboard/reports/', react_api.dashboard_reports_api, name='react_dashboard_reports_api'),
    path('api/dashboard/settings/', react_api.dashboard_settings_api, name='react_dashboard_settings_api'),
    path('api/dashboard/credentials/<int:student_id>/', react_api.dashboard_credentials_api, name='react_dashboard_credentials_api'),
    path('api/dashboard/bulk-upload/', react_api.dashboard_bulk_upload_api, name='react_dashboard_bulk_upload_api'),
    path('api/dashboard/print-controls/', react_api.dashboard_print_controls_api, name='react_dashboard_print_controls_api'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__reload__/", include("django_browser_reload.urls"))]
